#! /bin/sh

# cursor fix 
xsetroot -cursor_name left_ptr

# set workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# gaps
bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"

# color preselect
bspc config presel_feedback_color "fd2e59"

# size of main window
bspc config split_ratio          0.5

# enable mouse focus
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

# disable monocle for single window
bspc config single_monocle	     false

# disable gaps for single window
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

# window rules
bspc rule -a firefox follow=off desktop='^9'
bspc rule -a discord follow=off desktop='^3'
bspc rule -a TelegramDesktop state=floating follow=off desktop='^8'
#bspc rule -a TelegramDesktop state=floating follow=off rectangle=500x930+90+90 desktop='^8'
bspc rule -a Steam state=floating follow=off rectangle=1350x900+285+90 desktop='^10' 
bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
bspc rule -a ru-turikhay-tlauncher-bootstrap-Bootstrap state=floating follow=off desktop='^3'
