#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

main() {
	case "$class" in
		Blueman-manager)
			echo "state=floating rectangle=400x500+0+0"
			;;
		Transmission-gtk)
			echo "follow=off desktop=^6"
			;;
		Spotify)
			echo "follow=off desktop=^3"
			;;
		Element)
			echo "state=floating follow=off rectangle=1150x930+680+90 desktop=^2"
			;;
		"")
                        sleep 0.5

			wm_class=($(xprop -id $wid | grep "WM_CLASS" | grep -Po '"\K[^,"]+'))

			class=${wm_class[-1]}

			[[ ${#wm_class[@]} == "2" ]] && instance=${wm_class[0]}

			[[ -n "$class" ]] && main
			;;
	esac
}

main
